name: Test

on:
  push:
    branches: [main]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
  pull_request:
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: go vet
        run: go vet ./cmd/... ./internal/...

      - name: go test
        run: go test -race -count=1 ./cmd/... ./internal/...
